"use strict";
const $ = id => document.getElementById(id);
let data, mode = "council", selectedTrial = null;
const currency = value => value === null ? "Unavailable" : Number(value).toLocaleString("en-US", {style:"currency",currency:"USD",maximumFractionDigits:2});
const percent = value => value === null ? "Unavailable" : (Number(value)*100).toFixed(2)+"%";
const date = value => new Date(value).toLocaleDateString("en-US", {year:"numeric",month:"short",day:"numeric",timeZone:"UTC"});
function node(tag, text, cls) { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(cls)n.className=cls; return n; }
function metricValue(m, format=percent) { return m.value===null ? "Unavailable" : format(m.value); }
function evidenceLink(id, label="Saved evidence") { const a=node("a",label); a.href="#evidence/"+encodeURIComponent(id); a.addEventListener("click",e=>{e.preventDefault();openEvidence(id);}); return a; }
function openEvidence(id) { const item=data.evidence.find(e=>e.id===id); $("evidence-body").replaceChildren(); $("evidence-title").textContent=item?.label||"Evidence unavailable"; if(item){$("evidence-body").append(node("p",item.visibility==="private"?"Restricted provenance · inspect private storage":"Original fixture evidence","badge"),node("p",item.id,"meta")); for(const line of item.details)$("evidence-body").append(node("p",line));}else $("evidence-body").append(node("p","This evidence is not included in the allowlisted report."));$("evidence-dialog").showModal(); }
$("close-evidence").addEventListener("click",()=>$("evidence-dialog").close());
function table(headers, rows) {const wrap=node("div",undefined,"table-scroll"),t=node("table"),head=node("thead"),tr=node("tr");wrap.tabIndex=0;wrap.setAttribute("role","region");wrap.setAttribute("aria-label","Scrollable table: "+headers.join(", "));for(const h of headers){const th=node("th",h);th.scope="col";tr.append(th);}head.append(tr);t.append(head);const body=node("tbody");for(const row of rows){const r=node("tr");for(const item of row){const td=node("td");td.append(item instanceof Node?item:document.createTextNode(String(item)));r.append(td);}body.append(r);}t.append(body);wrap.append(t);return wrap;}
function svgNode(tag,attrs={}){const n=document.createElementNS("http://www.w3.org/2000/svg",tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function chart(card, baseline, kind="equity") {
 const svg=svgNode("svg",{viewBox:"0 0 700 240",role:"img","aria-label":kind==="equity"?"Equity history in US dollars. Exact values follow in the table.":"Drawdown history. Missing values are gaps; exact values follow in the table.",class:"chart"});
 const points=card.history, all=points.map(p=>p[kind]).filter(v=>v!==null).map(Number);
 if(kind==="equity"){all.push(Number(card.initial_cash)); if(baseline)all.push(...baseline.history.map(p=>p.equity).filter(v=>v!==null).map(Number));}
 if(!all.length){const text=svgNode("text",{x:65,y:95});text.textContent="No complete marks to plot";svg.append(text);return svg;}
 let lo=Math.min(...all),hi=Math.max(...all);const margin=Math.max((hi-lo)*.18,kind==="equity"?1:.0001);lo-=margin;hi+=margin;if(kind==="drawdown"){lo=0;hi=Math.max(.01,Math.max(...all)*1.15);}
 const x=i=>66+(points.length===1?0:i/(points.length-1)*610),y=v=>190-(Number(v)-lo)/(hi-lo)*160;
 for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3,yy=y(v);svg.append(svgNode("line",{x1:65,y1:yy,x2:680,y2:yy,stroke:"#e2e9ee"}));const text=svgNode("text",{x:0,y:yy+5});text.textContent=kind==="equity"?"$"+Math.round(v).toLocaleString("en-US"):(v*100).toFixed(2)+"%";svg.append(text);}
 function line(values,color,dashed=false){let path="",open=false;values.forEach((v,i)=>{if(v===null){open=false;return;}path+=(open?"L":"M")+x(i)+","+y(v)+" ";open=true;svg.append(svgNode("circle",{cx:x(i),cy:y(v),r:3,fill:color}));});svg.append(svgNode("path",{d:path,fill:"none",stroke:color,"stroke-width":2.5,...(dashed?{"stroke-dasharray":"6 5"}:{})}));}
 if(kind==="equity"){line(points.map(()=>card.initial_cash),"#8799a8",true);if(baseline)line(points.map(p=>baseline.history.find(b=>b.session===p.session)?.equity??null),"#7353a6");}
 line(points.map(p=>p[kind]),kind==="equity"?"#006d73":"#a33242");
 points.forEach((p,i)=>{const text=svgNode("text",{x:x(i),y:224,"text-anchor":i===0?"start":i===points.length-1?"end":"middle"});text.textContent=date(p.session);svg.append(text);});return svg;
}
function metricBox(label,value,note){const el=node("div",undefined,"metric");el.append(node("div",label,"metric-label"),node("div",value,"metric-value"),node("div",note,"metric-note"));return el;}
function details(card, version) {
 const result=node("section"); const heading=node("div",undefined,"heading"), title=node("div");title.append(node("h1",card.label),node("p",`${date(card.window_start)} – ${date(card.as_of)} · ${card.horizon}`,"muted"));const badges=node("div",undefined,"badges");for(const label of [card.evidence_grade,card.readiness,card.halted?"Risk halt":card.equity===null?"Stale data":"Reconciled"]){badges.append(node("span",label,"badge "+(label==="fixture"?"fixture":/halt|Stale/.test(label)?"alert":"")));}heading.append(title,badges);result.append(heading);
 result.append(node("p",`Frozen owner: ${card.owner_version} · ${card.heartbeat_status}`,"status-line"));
 const metrics=node("div",undefined,"metrics");metrics.append(metricBox("Fictional equity",currency(card.equity),"Cash "+currency(card.cash)),metricBox("Net return",metricValue(card.metrics.net_return),"Cash "+metricValue(card.cash_baseline)+" · Index "+metricValue(card.index_baseline)),metricBox("Maximum drawdown",metricValue(card.metrics.max_drawdown),card.metrics.max_drawdown.reason||"From highest recorded equity"),metricBox("Gross exposure",metricValue(card.metrics.gross_exposure),"Turnover "+metricValue(card.metrics.turnover)));result.append(metrics);
 const grid=node("div",undefined,"grid"),history=node("section",undefined,"panel");history.append(node("h2","Equity and drawdown"));const baseline=version.cards.find(c=>c.role==="index_baseline"&&c.regime===card.regime);history.append(chart(card,baseline));const legend=node("div",undefined,"legend");legend.append(node("span","Portfolio"),node("span","Cash","cash"),node("span","Index","index"));history.append(legend,chart(card,null,"drawdown"));const alt=node("details"),sum=node("summary","Exact history · table alternative");alt.append(sum,table(["Session","Equity","Drawdown","Quality"],card.history.map(p=>[date(p.session),currency(p.equity),percent(p.drawdown),p.reason||"Complete closing mark"])));history.append(alt);
 const outcome=node("section",undefined,"panel");outcome.append(node("h2","Decision quality"));const dl=node("dl",undefined,"compact");for(const [k,v]of [["Executed fills",card.fills],["Abstain / wait opinions",card.abstentions],["Matured forecasts",card.forecasts.matured],["Pending forecasts",card.forecasts.pending],["Unscorable outcomes",card.forecasts.unscorable],["Brier score",metricValue(card.metrics.brier,v=>Number(v).toFixed(4))],["Closed-position hit rate",metricValue(card.metrics.hit_rate)],["Trading fees",currency(card.fees)],["Dividend income",currency(card.income)],["Recorded model cost",metricValue(card.operating_cost,currency)]]){dl.append(node("dt",k),node("dd",v));}outcome.append(dl,node("p",card.metrics.hit_rate.reason||"Only fully closed positions count toward hit rate.","status-line"),node("p",`${card.trial_count} trials are retained. These samples do not establish skill.`,"status-line"));grid.append(history,outcome);result.append(grid);
 const lower=node("div",undefined,"grid"),holdings=node("section",undefined,"panel"),decisions=node("section",undefined,"panel");holdings.append(node("h2","Holdings"));holdings.append(card.holdings.length?table(["Instrument","Units","Value","Sector"],card.holdings.map(h=>[h.symbol,h.quantity,currency(h.value),h.sector])):node("p","No holdings. Cash remains a valid zero-interest baseline.","muted"));decisions.append(node("h2","Saved decisions and advice"));decisions.append(card.decisions.length?table(["Author / at","Recommendation","Outcome","Evidence"],card.decisions.map(d=>[`${d.author} · ${date(d.at)}`,`${d.action} · ${d.quantity} units`,d.outcome,evidenceLink(d.id,"Decision")])):node("p","No decisions recorded.","muted"));decisions.append(node("p",card.advice==="none"?"No-mail trial. No peer discussion was delivered.":"Bounded advice. Considering an objection does not mean accepting it.","status-line"));if(card.advice_log.length)decisions.append(table(["Mail","Disposition","Evidence"],card.advice_log.map(a=>[a.kind,a.status,evidenceLink(a.id,"Mail event")])));lower.append(holdings,decisions);result.append(lower);
 const explain=node("section",undefined,"panel"),button=node("button","Explain this result","explain"),answers=node("div",undefined,"answers");const aid="answers-"+card.report_id.slice(-12);answers.id=aid;answers.hidden=true;button.setAttribute("aria-expanded","false");button.setAttribute("aria-controls",aid);button.addEventListener("click",()=>{answers.hidden=!answers.hidden;button.setAttribute("aria-expanded",String(!answers.hidden));});explain.append(node("h2","Beliefs, learning and evidence"),node("p",`${card.learning.statement}. ${card.learning.checkpoints} saved checkpoints in this experiment.`,"muted"),button);card.answers.forEach((a,i)=>{const d=node("details");d.append(node("summary",`${i+1}. ${a.question}`),node("p",a.answer));const links=node("div",undefined,"evidence-links");for(const id of a.evidence_ids){const e=data.evidence.find(e=>e.id===id);links.append(evidenceLink(id,e?.label||"Evidence"));}d.append(links);answers.append(d);});explain.append(answers);result.append(explain);return result;
}
function version(){return data.versions[Number($("version").value)||0];}
function updateFilters(){const cards=version().cards.filter(c=>c.mode===mode&&c.role==="strategy");$("experiment").replaceChildren(new Option("All in this mode","all"));for(const c of cards)$("experiment").add(new Option(c.label,c.trial_id));$("horizon").replaceChildren(new Option("Any","all"));for(const h of new Set(cards.map(c=>c.horizon)))$("horizon").add(new Option(h,h));}
function render(){const v=version(),root=$("results");root.replaceChildren();root.setAttribute("aria-labelledby",mode==="council"?"council-tab":"characters-tab");const cards=v.cards.filter(c=>c.mode===mode&&c.role==="strategy"&&($("experiment").value==="all"||c.trial_id===$("experiment").value)&&($("advice").value==="all"||c.advice===$("advice").value)&&($("horizon").value==="all"||c.horizon===$("horizon").value));if(!cards.length){root.append(node("p","No saved portfolios match these filters. Choose another report or advice setting.","empty"));return;}
 if(mode==="character_portfolio"){const rows=cards.map(c=>{const b=node("button","View portfolio","row-action");b.addEventListener("click",()=>{selectedTrial=c.trial_id;render();$("results").focus();});return [node("strong",c.label),c.readiness,currency(c.equity),metricValue(c.metrics.net_return),c.equity===null?"Stale data":c.evidence_grade,b];});for(const c of data.roster)rows.push([c.name,c.status,"Unavailable","Unavailable",c.note,"No results"]);const p=node("section",undefined,"panel");p.append(node("h2","Independent capital. Separate evidence."),node("p","Every portfolio is separately funded. Values are not pooled or ranked across information regimes.","muted"),table(["Character","Readiness","Equity","Net return","Evidence","Inspect"],rows));root.append(p);}
 const selected=cards.find(c=>c.trial_id===selectedTrial)||cards[0];root.append(details(selected,v));
 const side=v.cards.filter(c=>c.role==="counterfactual"&&c.regime===selected.regime);if(side.length){const section=node("details",undefined,"panel support");section.append(node("summary","Rejected-decision counterfactual · separate capital"));for(const c of side)section.append(node("p",`${c.label}: ${currency(c.equity)}, ${c.fills} fills. The original risk limit is still enforced. This result is not added to the council return.`));root.append(section);}
 const registry=$("registry");registry.replaceChildren();const d=node("details");d.append(node("summary","Trial registry and out-of-sample review"),node("p","All declared trials remain visible, including failed or withdrawn trials. Meeting a sample floor does not authorize promotion."),table(["Trial","Role","Status"],data.registry.map(r=>[r.trial_id,r.role,r.status])));for(const c of data.comparisons)d.append(node("p",`Matched no-mail versus mail difference: ${metricValue(c.difference)}. ${c.interpretation}`));registry.append(d);
 $("provenance").textContent=`Data as of ${v.as_of} · Report generated ${data.generated_at} · ${data.redaction_policy} · ${data.source_run_ids.length} saved source runs. Historical versions retain their own evidence.`;
}
document.querySelectorAll("[role=tab]").forEach((tab,index,tabs)=>{tab.addEventListener("click",()=>{mode=tab.dataset.mode;selectedTrial=null;for(const t of tabs){t.setAttribute("aria-selected",String(t===tab));t.tabIndex=t===tab?0:-1;}updateFilters();render();});tab.addEventListener("keydown",event=>{let target;if(event.key==="ArrowRight")target=tabs[(index+1)%tabs.length];if(event.key==="ArrowLeft")target=tabs[(index+tabs.length-1)%tabs.length];if(event.key==="Home")target=tabs[0];if(event.key==="End")target=tabs[tabs.length-1];if(target){event.preventDefault();target.click();target.focus();}});});
$("version").addEventListener("change",()=>{updateFilters();render();});for(const id of ["experiment","advice","horizon"])$(id).addEventListener("change",render);
function canonical(value){if(Array.isArray(value))return "["+value.map(canonical).join(",")+"]";if(value&&typeof value==="object")return "{"+Object.keys(value).sort().map(k=>JSON.stringify(k)+":"+canonical(value[k])).join(",")+"}";return JSON.stringify(value);}
function conforms(value,schema){
 if(schema.anyOf)return schema.anyOf.some(s=>conforms(value,s));
 if("const"in schema&&value!==schema.const)return false;
 if(schema.enum&&!schema.enum.includes(value))return false;
 if(schema.type==="null")return value===null;
 if(schema.type==="object")return value!==null&&typeof value==="object"&&!Array.isArray(value)&&(schema.required||[]).every(k=>k in value)&&Object.keys(value).every(k=>k in schema.properties&&conforms(value[k],schema.properties[k]));
 if(schema.type==="array")return Array.isArray(value)&&value.length>=(schema.minItems||0)&&(!schema.uniqueItems||new Set(value.map(canonical)).size===value.length)&&value.every(v=>conforms(v,schema.items));
 if(schema.type==="string")return typeof value==="string"&&value.length>=(schema.minLength||0)&&(!schema.pattern||new RegExp(schema.pattern).test(value))&&(!schema.format||Number.isFinite(Date.parse(value)));
 if(schema.type==="boolean")return typeof value==="boolean";
 if(schema.type==="integer")return Number.isInteger(value)&&value>=(schema.minimum??-Infinity);
 return !("type"in schema);
}
async function verifyShape(d,schema){
 if(!conforms(d,schema))throw Error("Unsupported report format");
 const {content_hash,...body}=d;
 const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(body)));
 const hash=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");
 if(hash!==content_hash)throw Error("Report integrity mismatch");
 const evidence=new Set(d.evidence.map(e=>e.id));
 for(const version of d.versions)for(const card of version.cards){if(card.answers.length!==6||card.answers.some(a=>a.evidence_ids.some(id=>!evidence.has(id))))throw Error("Missing evidence");for(const m of [...Object.values(card.metrics),card.cash_baseline,card.index_baseline,card.operating_cost])if((m.value===null)===(m.reason===null))throw Error("Missing metric reason");}
}
async function load(){try{const responses=await Promise.all([fetch("report.json",{cache:"no-cache"}),fetch("schema.json",{cache:"no-cache"})]);if(responses.some(r=>!r.ok))throw Error("Report file missing");const [report,schema]=await Promise.all(responses.map(r=>r.json()));await verifyShape(report,schema);data=report;$("notice").textContent=data.notice;$("version").replaceChildren();data.versions.forEach((v,i)=>$("version").add(new Option(`${date(v.as_of)} · saved version`,String(i))));$("version").value=String(data.versions.length-1);updateFilters();render();$("load-state").hidden=true;$("app").hidden=false;}catch{const state=$("load-state");state.hidden=false;state.setAttribute("role","alert");state.replaceChildren(node("h1","Report unavailable"),node("p","The saved report is missing, incomplete or uses an unsupported format. Run evaluate and export locally, then open it with demo --serve and retry."));const retry=node("button","Retry saved report");retry.addEventListener("click",load);state.append(retry);$("app").hidden=true;}}
load();
