"use strict";
// Shared DOM/chart/dialog helpers come from app.js; legacy startup is disabled.
let privateMode="council", privateSelected=null;
const basisLabel=b=>b==="paper_broker"?"Broker paper":"Simulated";
const metricText=(m,f=percent)=>m.value===null?"Unavailable · "+m.reason:f(m.value);
const panel=title=>{const p=node("section",undefined,"panel");p.append(node("h2",title));return p;};
function privateVersion(){return data.versions[Number($("version").value)||0];}
function privateFilters(){
 const cards=privateVersion()?.cards||[];
 for(const [id,label,values]of [["experiment","All portfolio windows",cards.map(c=>c.performance.portfolio_id)], ["character","All versions",cards.map(c=>c.performance.owner_character_version)], ["regime","All, kept separate",cards.map(c=>c.regime)], ["horizon","Any",cards.map(c=>c.context.horizon)]]){
  const old=$(id).value;$(id).replaceChildren(new Option(label,"all"));for(const v of new Set(values)){const card=cards.find(c=>c.performance.portfolio_id===v||c.performance.owner_character_version===v);const label=id==="experiment"&&card?card.label:id==="character"&&card?card.label+" · "+v: v;$(id).add(new Option(label,v));}if([...$(id).options].some(o=>o.value===old))$(id).value=old;
 }
}
function privateDetails(card){
 const p=card.performance,c=card.context,result=node("section"),heading=node("div",undefined,"heading"),title=node("div");
 title.append(node("h1",card.label),node("p",`${basisLabel(p.execution_basis)} · ${card.role.replaceAll("_"," ")} · ${card.regime}`,"muted"));
 const badges=node("div",undefined,"badges");for(const text of [p.evidence_grade,card.readiness,p.halted?"Risk halt":"Admission not halted",p.equity.value===null?"Stale / unavailable valuation":"Eligible valuation"]){badges.append(node("span",text,"badge "+(/fixture/.test(text)?"fixture":/Risk halt|unavailable/.test(text)?"alert":"")));}
 heading.append(title,badges);result.append(heading,node("p",`Frozen owner: ${p.owner_character_version} · Funded segment: ${p.segment_id}`,"status-line"),node("p",`Window ${date(card.window_start)} – ${date(card.window_end)} · Effective ${p.effective_cutoff} · Known through ${p.receipt_cutoff} · Revision ${p.projection_revision}`,"status-line"));
 result.append(node("p",`Heartbeat: ${c.heartbeat_status==="no_data"?"No saved heartbeat":c.heartbeat_status} · Last success: ${c.last_successful_heartbeat||"Not recorded"}`,"status-line"));
 if(p.execution_basis==="paper_broker"){
 const message=node("div",undefined,"notice");message.append(node("p",card.matched_control_ids.length?"A matched simulated control is available. Its returns remain separate from broker fills.":"No matched simulated control is available in this saved view."));
 if(card.matched_control_ids.length){const button=node("button","Inspect simulated control");button.addEventListener("click",()=>{const control=privateVersion().cards.find(c=>c.performance.portfolio_id===card.matched_control_ids[0]);$("basis").value="simulated";for(const id of ["experiment","character","advice","horizon","regime"])$(id).value="all";privateSelected=control.report_id;renderPrivate();$("results").focus();});message.append(button);}result.append(message);
 }
 const metrics=node("div",undefined,"metrics");metrics.append(metricBox("Equity",metricValue(p.equity,currency),p.equity.reason||"Total cash "+currency(p.cash)),metricBox("After-cost TWR",metricValue(p.twr),p.twr.reason||"Cash "+metricText(p.cash_baseline)+" · Market "+metricText(p.broad_market_baseline)),metricBox("Flow-neutral drawdown",metricValue(p.max_drawdown),p.max_drawdown.reason||"From peak linked wealth"),metricBox("Exposure",metricValue(card.exposure),card.exposure.reason||"Turnover "+metricText(p.turnover)));result.append(metrics);
 const grid=node("div",undefined,"grid"),history=panel("Equity and flow-neutral drawdown"),quality=panel("Decision quality and costs");
 const series={history:p.history.map(h=>({...h,session:h.at})),initial_cash:p.initial_funding};
 history.append(chart(series,null,"equity",false),node("p","Portfolio dollars · external flows can move this line. Returns and drawdown remove those flows.","status-line"),chart(series,null,"drawdown",false));
 const exact=node("details");exact.append(node("summary","Exact history · table alternative"),table(["At (UTC)","Equity","Wealth index","Drawdown","Quality"],p.history.map(h=>[h.at,currency(h.equity),h.wealth??"Unavailable",percent(h.drawdown),h.reason||"Eligible"])));history.append(exact);
 const dl=node("dl",undefined,"compact");for(const [label,val]of [["Matured forecasts",c.forecasts.matured],["Pending outcomes",c.forecasts.pending],["Unscorable outcomes",c.forecasts.unscorable],["Brier score",metricText(c.forecasts.brier,v=>Number(v).toFixed(4))],["Saved abstentions",c.abstentions],["Closed-position hit rate",metricText(p.hit_rate)],["FIFO relief win rate",metricText(p.lot_relief_win_rate)],["Trading fees",currency(p.fees)],["Recurring operating expense",metricText(p.recurring_expense,currency)],["One-time learning/development",metricText(p.one_time_expense,currency)],["Economics P/L",metricText(p.economics_pnl,currency)],["Scheduled volatility",metricText(p.volatility)]])dl.append(node("dt",label),node("dd",val));quality.append(dl,node("p","Forecast samples describe decision evidence, not proof of skill. Costs do not overwrite trading TWR.","status-line"));grid.append(history,quality);result.append(grid);
 const cash=panel("Cash, P/L and distributions");cash.append(table(["Total cash","Available","Reserved","Dividend receivables","Initial funding","Net external flows"],[[currency(p.cash),currency(p.available),currency(p.reserved),currency(p.receivables),currency(p.initial_funding),currency(p.net_external_flows)]]),table(["FIFO basis","Realized","Unrealized","Dividend income","Strategy P/L"],[[currency(p.fifo_basis),currency(p.realized),metricText(p.unrealized,currency),currency(p.income),metricText(p.strategy_pnl,currency)]]));result.append(cash);
 const lower=node("div",undefined,"grid support"),lots=panel("Holdings and FIFO lots"),decisions=panel("Saved decisions and advice");
 lots.append(p.holdings.length?table(["Instrument","Units","Value","FIFO basis"],p.holdings.map(h=>[h.instrument_id,h.quantity,currency(h.value),currency(h.fifo_basis)])):node("p","No holdings. A cash-only or no-trade result is valid; it is not a claim of skill."));
 const lotDetails=node("details");lotDetails.append(node("summary","FIFO lots and reliefs"),table(["Acquired","Instrument","Remaining units","Remaining basis","Average basis / unit"],card.lots.map(l=>[date(l.acquired_at),l.instrument_id,l.quantity,currency(l.basis),currency(l.average_basis)])),table(["Sale","Quantity","Allocated basis","Proceeds","Disposal fees"],card.reliefs.map(r=>[r.sale_id,r.quantity,r.basis,r.proceeds,r.fees])));lots.append(lotDetails);
 decisions.append(card.decisions.length?table(["At / action","Units","Outcome","Evidence"],card.decisions.map(d=>[`${date(d.at)} · ${d.action}`,d.quantity,d.outcome,evidenceLink(d.id,"Decision")])):node("p","No trade decisions recorded. An empty trade ledger is not automatically an authored abstention."),node("p",c.advice==="none"?"No saved advice access in this context.":"Bounded advice; objections may remain unresolved.","status-line"));
 if(c.advice_log.length)decisions.append(table(["Author / kind","Disposition","Saved summary"],c.advice_log.map(a=>[`${a.author_version} · ${a.kind}`,a.status,a.summary])));lower.append(lots,decisions);result.append(lower);
 const audit=panel("External flows, marks and reconciliation");audit.append(table(["At (UTC)","Flow","Amount"],card.flows.map(f=>[f.at,f.kind,currency(f.amount)])),table(["Instrument","Market time","Received","Feed / revision","Status","Evidence"],card.marks.map(m=>[m.instrument_id,m.event_at,m.received_at,`${m.feed} · r${m.revision}`,m.status+(m.reason?" · "+m.reason:""),evidenceLink(m.id,"Mark")])),node("p",`Reconciliation: ${card.reconciliation.status}. ${card.reconciliation.differences.join("; ")}`,"status-line"));result.append(audit);
 const explain=panel("Beliefs, learning and evidence"),button=node("button","Explain this result","explain"),answers=node("div",undefined,"answers");
 answers.id="private-answers";answers.hidden=true;button.setAttribute("aria-expanded","false");button.setAttribute("aria-controls",answers.id);button.addEventListener("click",()=>{answers.hidden=!answers.hidden;button.setAttribute("aria-expanded",String(!answers.hidden));});
 explain.append(node("p",c.learning_statement),node("p",c.learning_total?`${c.learning_completed} / ${c.learning_total} declared learning units complete. Readiness: ${card.readiness}.`:`Learning progress unavailable. Readiness: ${card.readiness}.`,"status-line"),button);
 card.answers.forEach((a,i)=>{const d=node("details"),links=node("div",undefined,"evidence-links");d.append(node("summary",`${i+1}. ${a.question}`),node("p",a.answer));for(const id of a.evidence_ids)links.append(evidenceLink(id,data.evidence.find(e=>e.id===id)?.label||"Evidence"));d.append(links);answers.append(d);});explain.append(answers);result.append(explain);
 const limits=panel("Evidence grade and open limitations");limits.append(node("p",`${p.evidence_grade} · No promotion decision is made by this view.`));const ul=node("ul");for(const reason of [...p.review_blockers,...p.gaps])ul.append(node("li",reason));limits.append(ul);result.append(limits);return result;
}
function renderPrivate(){
 const root=$("results"),v=privateVersion();root.replaceChildren();$("registry").replaceChildren();root.setAttribute("aria-labelledby",privateMode==="council"?"council-tab":"characters-tab");
 const cards=(v?.cards||[]).filter(c=>{const p=c.performance;return p.mode===privateMode&&p.execution_basis===$("basis").value&&c.role!=="baseline"&&[ ["experiment",p.portfolio_id],["character",p.owner_character_version],["regime",c.regime],["advice",c.context.advice],["horizon",c.context.horizon] ].every(([id,val])=>$(id).value==="all"||$(id).value===val);});
 const list=panel(privateMode==="council"?"Monarchy · one lead, bounded advice":"Individual · independently funded portfolios");list.append(node("p","Rows retain their own regime, version and capital. They are not sorted by return or pooled.","muted"));
 const rows=cards.map(c=>{const b=node("button","View "+c.label,"row-action");b.addEventListener("click",()=>{privateSelected=c.report_id;renderPrivate();$("results").focus();});return [c.label,c.readiness,c.regime,basisLabel(c.performance.execution_basis),metricText(c.performance.twr),b];});
 if(privateMode==="character_portfolio")for(const c of data.roster.filter(r=>!data.versions.some(v=>v.cards.some(c=>c.performance.owner_character_version===r.id))&&($("character").value==="all"||$("character").value===r.id)))rows.push([`${c.name} · ${c.version}`,c.readiness,"No result in this selection","Simulated only","Unavailable",c.note]);
 list.append(table(["Character / portfolio","Readiness","Regime","Execution","TWR","Inspect"],rows));root.append(list);
 if(cards.length)root.append(privateDetails(cards.find(c=>c.report_id===privateSelected)||cards[0]));else root.append(node("p",data.versions.length?"No saved portfolios match these filters. Choose another execution basis, version or mode.":"No data yet. Save a v2 evaluation to inspect accounting; untrained Characters have no invented returns.","empty"));
 $("provenance").textContent=`Private owner v2 · Generated ${data.generated_at} · ${data.source_record_ids.length} source records · Saved effective and receipt cutoffs remain distinct. No model or account call on interaction.`;
}
document.querySelectorAll("[role=tab]").forEach((tab,index,tabs)=>{
 tab.addEventListener("click",()=>{privateMode=tab.dataset.mode;privateSelected=null;for(const t of tabs){t.setAttribute("aria-selected",String(t===tab));t.tabIndex=t===tab?0:-1;}renderPrivate();});
 tab.addEventListener("keydown",event=>{const next=event.key==="ArrowRight"?tabs[(index+1)%tabs.length]:event.key==="ArrowLeft"?tabs[(index+tabs.length-1)%tabs.length]:event.key==="Home"?tabs[0]:event.key==="End"?tabs[tabs.length-1]:null;if(next){event.preventDefault();next.click();next.focus();}});
});
$("version").addEventListener("change",()=>{privateSelected=null;privateFilters();renderPrivate();});
for(const id of ["experiment","character","regime","basis","advice","horizon"])$(id).addEventListener("change",()=>{privateSelected=null;renderPrivate();});
document.querySelector(".skip").addEventListener("click",event=>{event.preventDefault();$("main").focus();});
async function loadPrivate(){try{
 const responses=await Promise.all([fetch("report.json",{cache:"no-store"}),fetch("schema.json",{cache:"no-store"})]);if(responses.some(r=>!r.ok))throw Error("Missing report");
 const [report,schema]=await Promise.all(responses.map(r=>r.json()));if(!conforms(report,schema)||report.publication_class!=="private-owner-v2")throw Error("Invalid private shape");
 const {content_hash,...body}=report;const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(body)));if(Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("")!==content_hash)throw Error("Integrity mismatch");
 const ids=new Set(report.evidence.map(e=>e.id));for(const v of report.versions)for(const c of v.cards)if(c.answers.length!==6||c.answers.some(a=>a.evidence_ids.some(id=>!ids.has(id))))throw Error("Missing evidence");
 data=report;$("notice").textContent=data.notice;$("version").replaceChildren();data.versions.forEach((v,i)=>$("version").add(new Option(`Effective ${date(v.as_of)} · known ${date(v.receipt_cutoff)}`,String(i))));$("version").value=String(Math.max(0,data.versions.length-1));privateFilters();renderPrivate();$("load-state").hidden=true;$("app").hidden=false;
 }catch{const state=$("load-state");state.hidden=false;state.setAttribute("role","alert");state.replaceChildren(node("h1","Private report unavailable"),node("p","The saved bundle is incomplete, invalid or missing. Rebuild it from validated private evidence; the previous valid report remains on disk."));$("app").hidden=true;}}
loadPrivate();
